### ISSUE TITLE
Request: Error moving media file should skip file

### ISSUE THREAD

**Issue by scuppasteve** [StudioNirin/PlexCache-R#27]
**Is your feature request related to a problem? Please describe.**
When the script can't find a file it errors and stops the script. 

CRITICAL - Error moving media files to cache: FileNotFoundError: [Errno 2] No such file or directory: 

**Describe the solution you'd like**
I would like it to skip that file and continue the rest of the script.

**Comment by Brandon-Haney** [comment]
Hi, @scuppasteve can you attach a full log for review?

**Comment by scuppasteve** [comment]
[plexcache_log_20251210_1600.log](https://github.com/user-attachments/files/24119288/plexcache_log_20251210_1600.log)

Please see attached.

**Comment by Brandon-Haney** [comment]
This issue is directly caused by the bug reported in Issue #28 (double path conversion).

Looking at your log:

> Adding file to cache: /mnt/user/data/media/mnt/user/data/media/tv-h-r/New Girl...
> CRITICAL - Error moving media files to cache: FileNotFoundError: '/mnt/user/data/media/mnt/user/data/media/...'

The path /mnt/user/data/media/mnt/user/data/media/... is malformed - mnt/user/data/media appears twice. 

Fixing #28 will resolve your immediate issue. Once paths are correctly converted, the files will exist and no FileNotFoundError will occur.

**Comment by scuppasteve** [comment]
Seems you are correct, i am going to close this.

**Comment by scuppasteve** [comment]
Hey i finally got around to running the mapping fix on my other two servers, and for some reason they are both failing due to missing files. I have attached the two logs. Thanks much.

[plexcache_settings(movieserver).json](https://github.com/user-attachments/files/24417519/plexcache_settings.movieserver.json)
[plexcache_settings(tvserver1).json](https://github.com/user-attachments/files/24417521/plexcache_settings.tvserver1.json)
[plexcache_log_20251227_1136(tvserver01).log](https://github.com/user-attachments/files/24417520/plexcache_log_20251227_1136.tvserver01.log)
[plexcache_log_20251227_1114(movieserver).log](https://github.com/user-attachments/files/24417518/plexcache_log_20251227_1114.movieserver.log)

**Comment by Brandon-Haney** [comment]
> Hey i finally got around to running the mapping fix on my other two servers, and for some reason they are both failing due to missing files. I have attached the two logs. Thanks much.
> 
> [plexcache_settings(movieserver).json](https://github.com/user-attachments/files/24417519/plexcache_settings.movieserver.json) [plexcache_settings(tvserver1).json](https://github.com/user-attachments/files/24417521/plexcache_settings.tvserver1.json) [plexcache_log_20251227_1136(tvserver01).log](https://github.com/user-attachments/files/24417520/plexcache_log_20251227_1136.tvserver01.log) [plexcache_log_20251227_1114(movieserver).log](https://github.com/user-attachments/files/24417518/plexcache_log_20251227_1114.movieserver.log)

Are you running main or this branch https://github.com/StudioNirin/PlexCache-R/tree/v2.0-branch-main

We should have this resolved via the commit here 1e5c16d, please confirm your version for me.

**Comment by scuppasteve** [comment]
> Are you running main or this branch https://github.com/StudioNirin/PlexCache-R/tree/v2.0-branch-main

I believe i am running PlexCache-R v1.3. I couldn't find a version on the files, but my file dates are all before v2.0 branch. Should i switch to the 2.0 branch?

**Comment by StudioNirin** [comment]
> > Are you running main or this branch https://github.com/StudioNirin/PlexCache-R/tree/v2.0-branch-main
> 
> I believe i am running PlexCache-R v1.3. I couldn't find a version on the files, but my file dates are all before v2.0 branch. Should i switch to the 2.0 branch?

Oh sorry I didn't notice that this auto-closed when I did the recent merge. 

I would however recommend updating to v2.0 at this point, as it's the version we will be working on and supporting and there has been a TON of updates and improvement in it. 

I've reopened this issue for now, until @scuppasteve can report back and say if he's still having problems with sometime.

**Comment by scuppasteve** [comment]
> I've reopened this issue for now, until [@scuppasteve](https://github.com/scuppasteve) can report back and say if he's still having problems with sometime.

@StudioNirin I figured yesterday when it closed that i should move to the new version. New version works great, i am closing this.
